set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
" Javascript indentation plugin
Plugin 'pangloss/vim-javascript'
" Automate braces
Plugin 'Raimondi/delimitMate'
" Javascript Lynt
Plugin 'scrooloose/syntastic'
" STL Syntax
Plugin 'Mizuchi/STL-Syntax'
" Auto completion
Plugin 'Valloric/YouCompleteMe'
" Git plugin
Plugin 'tpope/vim-fugitive'
" Doxygen
Plugin 'mrtazz/DoxygenToolkit.vim'
" YCM generator
Plugin 'rdnetto/YCM-Generator'
" CPP format for vim
Plugin 'rhysd/vim-clang-format'
call vundle#end()
filetype plugin indent on
set t_Co=256
syntax on
autocmd FileType cpp ClangFormatAutoEnable
set background=dark
" Show line and col number
set ruler
" Allow backspace over inset session"
set backspace=indent,eol,start

